# Generated by Django 2.1.5 on 2019-04-01 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('Registration', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=50)),
                ('Course_code', models.CharField(max_length=8)),
                ('File', models.FileField(upload_to='dbms/pdf/')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Project_title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Status', models.CharField(default='Pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Registration', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Course', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('pswd', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_id', models.CharField(max_length=15)),
                ('pswd', models.CharField(max_length=15)),
                ('Course', models.CharField(max_length=50)),
                ('Course_code', models.CharField(max_length=8)),
            ],
        ),
    ]
