# Generated by Django 2.1.5 on 2019-04-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Course_code',
        ),
    ]
