# Generated by Django 2.1.5 on 2019-04-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0002_auto_20190402_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Course',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Course_code',
            field=models.CharField(default='none', max_length=8),
        ),
    ]
